/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Progress:": "进度:",
    "Production:": "生产:",
    "Generated:": "生成:",
    "Bought:": "已购买:",
    "Idle Ant Farm": "放置蚂蚁农场",
    "Got it": "知道了",
    "Locked": "未解锁",
    "More": "更多",
    "Nursery": "苗圃",
    "Unlock Nursery": "解锁苗圃",
    "Worker Ant": "工蚁",
    "Worker Ants": "工蚁",
    "Your colony has been hibernating for": "您的蚁群已处于休眠状态",
    "What's New in Idle Ant Farm": "放置蚂蚁农场的新动向",
    "We use cookies and similar technologies to analyze traffic, enhance site functionality, and improve your experience. By clicking \"Accept\", you consent to the use of cookies for analytics purposes.": "我们使用cookie和类似的技术来分析流量、增强网站功能和改善您的体验。点击“接受”，即表示您同意将cookie用于分析目的。",
    "Accept": "接受",
    "Adventure": "冒险",
    "Changed": "变更",
    "Continue": "继续",
    "Decline": "拒绝",
    "Evolution": "进化",
    "colony": "蚁群",
    "Colony": "蚁群",
    "Base Production:": "基础生产:",
    "Base × Multiplier:": "基础 × 乘数:",
    "Ant Hierarchy": "蚂蚁等级体系",
    "Foraging Trip": "觅食之旅",
    "Gathers food and materials for the colony": "为蚁群收集食物和材料",
    "Inventory": "库存",
    "Purchase 5 nurseries to unlock Evolution": "购买 5 个苗圃以解锁进化",
    "Unlock Adventure Mode from the Evolution tab (50 EP)": "从进化选项卡解锁冒险模式（50 进化点数）",
    ". We're calculating the progress made during this time.": "。我们正在计算这段时间的进度。",
    "Colony Hibernation Progress": "蚁群休眠进度",
    "Worker Ants Adaptations": "工蚁改造",
    "Worker Base": "工蚁基础",
    "Worker Training": "工蚁训练",
    "Worker Endurance": "工蚁耐力",
    "Worker Efficiency": "工蚁效率",
    "Upgrade Specialization": "专精升级",
    "Workers can carry more food per trip": "工蚁们每次可以携带更多的食物",
    "Workers find higher quality food sources": "工蚁们可以找到更高质量的食物来源",
    "Buy me a coffee": "请作者喝咖啡",
    "Colony Status": "蚁群状态",
    "Food": "食物",
    "Food/Trip": "食物/旅行",
    "Remember to export your save!": "记得导出您的存档！",
    "Report Issues": "报告问题",
    "Specialization:": "专精:",
    "Advanced Foraging": "高级觅食",
    "Available Adaptations": "可用的改造",
    "Available Points": "可用点数",
    "Current Level": "当前等级",
    "Effect:": "效果:",
    "Level:": "等级:",
    "Levels up based on ticks in current evolution": "根据当前进化中的 Tick 来升级",
    "Next:": "下一个:",
    "Progress to Next Level": "到达下一级的进度",
    "Return to Dashboard": "返回仪表板",
    "Achievement Unlocked!": "成就已解锁！",
    "Dedicated": "专注",
    "First Snack": "第一道点心",
    "Food Stock": "粮食储备",
    "MAX LEVEL": "最大等级",
    "Maxed": "已满级",
    "Unlock Queen Chamber": "解锁蚁后室",
    "Worker Army": "工蚁部队",
    "Worker Legion": "工蚁军团",
    "Small Pantry": "小储藏室",
    "Queen Chamber": "蚁后室",
    "queenChamber": "蚁后室",
    "Nutritional Wealth": "营养财富",
    "Nurtures new queens": "培育新蚁后",
    "Food Hoarder": "食物囤积者",
    "Better nutrition leads to faster worker development": "更好的营养导致工蚁更快的发展",
    "Decreases the cost of nurseries": "降低苗圃的成本",
    "Increases base worker production of nurseries by 1": "使苗圃的基本工蚁产量提高1",
    "Increases worker ant production of nurseries": "增加苗圃的工蚁产量",
    "Larval Nutrition": "幼虫营养",
    "Levels up based on amount of food gained": "根据获得的食物数量提升等级",
    "Nurseries can care for more larvae simultaneously": "苗圃可以同时照顾更多的幼虫",
    "Nursery Adaptations": "苗圃改造",
    "Nursery Base": "苗圃基础",
    "Nursery Capacity": "苗圃容量",
    "Nursery Efficiency": "苗圃效率",
    "Nursery Expansion": "苗圃扩建",
    "General": "常规",
    "Colony Manager": "蚁群经理",
    "Ant Enthusiast": "蚂蚁爱好者",
    "Achievement Bonuses": "成就加成",
    "Complete more achievements to earn additional bonuses!": "完成更多的成就来获得额外的奖励！",
    "Complete tasks to earn rewards and recognition": "完成任务以获得奖励和认可",
    "Cosmic Consumables": "宇宙耗材",
    "Decillion Dinner": "千兆晚宴",
    "Duodecillion Delicacies": "Duodecillion美食",
    "Endless Buffet": "无尽的自助餐",
    "Food Empire": "美食帝国",
    "Food Mountain": "食物山",
    "Food Supply Chain": "食物供应链",
    "Googol Gastronomy": "Googol美食",
    "Hungry Beginnings": "饥饿的开端",
    "Hyperdimensional Hunger": "超次元饥饿",
    "Infinite Ingestion": "无限摄取",
    "Interdimensional Feast": "跨次元盛宴",
    "More Options": "更多选择",
    "Multiversal Meals": "多种膳食",
    "Nonillion Nourishment": "百万营养",
    "nurseries": "苗圃",
    "Nurseries": "苗圃",
    "Octillion Omelets": "八万亿煎蛋卷",
    "Octillion Overstock": "八万亿库存过剩",
    "Play for 1 day in total": "总共玩1天",
    "Play for 1 week in total": "总共玩1周",
    "Quantum Nutrients": "量子营养",
    "Quantum Realm Cuisine": "量子王国美食",
    "Quattuordecillion Quantities": "超位数量",
    "Quintillion Quotient": "百万亿系数",
    "Septillion Stores": "千万亿商店",
    "Septillion Supper": "千万亿晚餐",
    "Sextillion Snack": "千万亿零食",
    "Sextillion Surplus": "千万亿盈余",
    "Transcendent Treats": "超然的款待",
    "Tredecillion Treats": "十兆糖果",
    "Trigintillion Triumph": "千兆凯旋",
    "Undecillion Utopia": "不亿亿乌托邦",
    "Universal Eatery": "万能餐厅",
    "Unlimited Appetite": "食欲无限",
    "Workers": "工蚁",
    "Cycle Requirements": "周期要求",
    "cycles required": "周期要求",
    "Evolution Points": "进化点数",
    "Expands your ant empire": "扩张你的蚂蚁帝国",
    "Foraging Cycles Completed": "觅食周期完成",
    "Metamorphosis": "蜕变",
    "Metamorphosis Count": "蜕变次数",
    "Unlock Colony": "解锁蚁群",
    "View Evolutionary Adaptations": "查看进化改造",
    "What is Metamorphosis?": "什么是蜕变？",
    "Metamorphosis allows you to evolve your colony and gain powerful bonuses. Purchase ants and other generators to increase your Evolution Points (EP).": "蜕变允许你进化你的蚁群并获得强大的奖励。购买蚂蚁和其他生成器来增加你的进化点数（EP）。",
    "Click the": "点击",
    "Evolution Requirement": "进化要求",
    "food collected": "已收集食物",
    "Food Progress": "食物进度",
    "Food Progress towards Next Cycle": "朝向下一周期的食物进度",
    "Foraging Cycles": "觅食周期",
    "Metamorphose": "蜕变",
    "Metamorphosis Status": "蜕变状态",
    "Potential Gain": "潜在收益",
    "Shows how many foraging trips you've completed toward the next cycle.": "显示你在下一个周期中完成了多少次觅食。",
    "Shows how much food you've collected toward instantly completing a cycle.": "显示你已经收集了多少食物，以便立即完成一个周期。",
    "to evolve. Each cycle requires either:": "以进化。每个周期需要：",
    "Trip Progress": "旅行进度",
    "Trip Progress towards Next Cycle": "前往下一个周期的旅行进度",
    "trips": "旅行",
    "You need": "你需要",
    "You need to evolve to access the upgrades.": "你需要进化才能获得升级。",
    "Your ants automatically make trips over time. Upgrades can speed this up or allow more simultaneous trips.": "随着时间的推移，你的蚂蚁会自动旅行。升级可以加快速度或允许更多的同时旅行。",
    "Bonus from achievements with EP boost.": "来自成就与进化点数提升的加成。",
    "button above for more detailed information.": "上面的按钮查看更多详细信息。",
    "Collecting enough food is an alternative way to complete cycles, especially useful later in the game.": "收集足够的食物是完成周期的另一种方式，在游戏后期尤其有用。",
    "Confirm Metamorphosis": "确认蜕变",
    "Cancel": "取消",
    "You are about to metamorphose your colony. You will gain": "你即将使你的蚁群蜕变。你会得到",
    "Your equipped items are enhancing your evolution potential, providing a bonus to EP gain.": "你装备的物品增强了你的进化潜力，提供了额外的进化点数增益。",
    "蚁群Your progress will reset, but your evolutionary adaptations will remain.": "你的进度将会重置，但你的进化改造将会保留。",
    "Decreases the cost of queen chambers": "降低蚁后室的成本",
    "Increases base nursery production of queen chambers by 1": "增加蚁后室的基础育婴室产量1",
    "Increases nursery production of queen chambers": "增加蚁后室的产量",
    "Levels up based on total manual purchases": "基于手动购买总数升级",
    "Queen Chamber Adaptations": "蚁后室改造",
    "Queen Chamber Base": "蚁后室基础",
    "Queen chambers occasionally create new queens": "蚁后室偶尔会产生新的蚁后",
    "Queen Efficiency": "蚁后效率",
    "Queen Fertility": "蚁后生育",
    "Queen Longevity": "蚁后长寿",
    "Queens enhance evolution potential, increasing EP gain by 0.05% per level per manual purchase of queen chamber per evolution done": "蚁后增强进化潜力，每级每手动购买蚁后室每次进化增加0.05%的EP增益",
    "Royal Evolution": "皇家进化",
    "Royal Guards": "皇家卫队",
    "Royal Jelly": "蚁后浆",
    "Special food increases queen egg production": "特殊食物可以增加蚁后卵的产量",
    "Special guards protect the queen, increasing productivity": "特别警卫保护蚁后，提高生产力",
    "Advanced Nursery Techniques": "高级苗圃技术",
    "Adventure Mode": "冒险模式",
    "All production increases by 2% per level, compounding with other upgrades": "所有产量每升一级增加2%，与其他升级相结合",
    "Auto Merge": "自动合并",
    "Automatically purchases Colonies each tick. Each level increases purchases per tick.": "每Tick自动购买蚁群。每级都会增加每Tick的购买量。",
    "Automatically purchases Nurseries each tick. Each level increases purchases per tick.": "每Tick自动购买苗圃。每级都会增加每Tick的购买量。",
    "Automatically purchases Queen Chambers each tick. Each level increases purchases per tick.": "每Tick自动购买蚁后室。每级都会增加每Tick的购买量。",
    "Automatically purchases Worker Ants each tick. Each level increases purchases per tick.": "每Tick自动购买工蚁。每级都会增加每Tick的购买量。",
    "Automation": "自动化",
    "Boosts worker ants by 5%, nurseries by 2.5%, and EP gain by 10% per level": "每升一级增加工蚁5%，苗圃2.5%，进化点数增加10%",
    "Bulk Automation": "批量自动化",
    "Colony Automation": "蚁群自动化",
    "Compound Evolution": "复合进化",
    "Cost (High to Low)": "成本（从高到低）",
    "Cost (Low to High)": "成本（从低到高）",
    "Cycle Food Reduction": "循环减少食物",
    "Decreases cycle time by 0.2 seconds per level": "每级减少0.2秒循环时间",
    "Divides the cost of workers by 1500 per level": "将工蚁成本除以每层1500",
    "Doubles the amount of food produced per level": "每级生产的粮食翻倍",
    "Each evolution completed boosts production by 1% per level": "每完成一次进化，每级的产量都会提高1%",
    "Each generator type boosts all others by 2% per level": "每种类型的生成器每升一级能提升其他所有生成器2%",
    "Early Multi-Tier Enhancement": "早期多层增强",
    "Efficiency": "效率",
    "Evolution Mastery": "进化精通",
    "Evolution Synergy": "协同进化",
    "Evolution Wealth": "进化的财富",
    "Faster Food Processing": "快速食物加工",
    "First Evolution": "第一次进化",
    "Generator Synergy": "生成器的协同作用",
    "Hide Maxed": "隐藏已达上限",
    "Increase maximum inventory slots by 5. Each level adds more slots, but costs increase rapidly.": "最大库存槽位增加5个。每个等级都会增加更多槽位，但成本也会迅速增加。",
    "Increases Evolution Points gained per cycle by 10% per level": "每升一级，每循环获得的进化点数增加10%",
    "Increases food production by 10% per level": "每升一级增加10%的粮食产量",
    "Increases overall colony efficiency by 5% per level": "每级增加蚁群整体效率5%",
    "Inventory Expansion": "库存扩张",
    "Level (High to Low)": "等级（从高到低）",
    "Level (Low to High)": "等级（从低到高）",
    "Multiplies the effectiveness of all automation upgrades": "增加所有自动化升级的有效性",
    "Mutated Worker Ants": "突变工蚁",
    "Name (A to Z)": "名称（从A到Z）",
    "Name (Z to A)": "名称（从Z到A）",
    "Nurseries have a 1% chance per level to reproduce themselves each tick (max 5%)": "苗圃每级有1%的机会繁殖自己（最多5%）",
    "Nurseries produce 25% more worker ants per level": "每一层托儿所生产的工蚁增加25%",
    "Nursery Automation": "苗圃自动化",
    "Nursery Self-Replication": "苗圃自我复制",
    "Perform 1 evolution": "进行1次进化",
    "Prestige": "声望",
    "Prestige Acceleration": "声望加速",
    "Production": "生产",
    "Queen Chamber Automation": "蚁后室自动化",
    "Reduces the food required for each cycle by 5% per level (max 75%)": "每级减少循环所需食物5%（最高75%）",
    "Reproduction": "繁殖",
    "Research": "研究",
    "Show Affordable": "显示可负担得起的",
    "Show Unlocked": "显示解锁",
    "Start with 10x more food per level after evolution": "进化后，每等级增加10倍的食物",
    "Start with more cycles completed after evolution": "从进化后完成的更多周期开始",
    "Starting Resources": "初始资源",
    "Stronger Soldier Ants": "更强壮的兵蚁",
    "Synergy": "协同作用",
    "Time Manipulation": "时间操纵",
    "Unlock Adventure mode and the Inventory system": "解锁冒险模式和背包系统",
    "Unlock automatic merging of items in your inventory": "解锁背包内物品自动合成功能",
    "Worker ants produce 20% more food per level": "工蚁每级能多生产20%的食物",
    "Worker Automation": "工蚁自动化",
    "Worker Cost Discount": "工蚁成本折扣",
    "Worker Self-Replication": "工蚁自我复制",
    "Workers have a 1% chance per level to reproduce themselves each tick (max 5%)": "工蚁每级有1%的机会复制自己（最多5%）",
    "Unlocked": "已解锁",
    "Max": "最大",
    "Small bonus based on total number of evolutions completed.": "根据累计进化次数获得少量奖励。",
    "Achievement Notifications": "成就通知",
    "Auto-Enable Auto Purchases After Evolution": "进化后自动启用汽车购买",
    "Automatically enable all auto-purchases after evolving": "进化后自动启用所有的自动购买",
    "Automatically save your colony progress every minute": "每分钟自动保存你的蚁群进度",
    "Calculate colony progress while you're away": "计算你离开时的蚁群进度",
    "Choose Save File": "选择“保存文件”",
    "Colony data exported successfully!": "蚁群数据导出成功！",
    "Colony Memory Management": "蚁群内存管理",
    "Colony saved successfully!": "成功保存蚁群！",
    "Colony Settings": "蚁群设置",
    "Copy this code to save your colony data:": "复制此代码以保存您的蚁群数据：",
    "Dark Mode": "深色模式",
    "Evolution Settings": "进化设置",
    "Export as Code": "代码导出",
    "Export as File": "导出为文件",
    "Export/Import Colony Data": "导出/导入蚁群数据",
    "Game Information": "游戏信息",
    "Game Version:": "游戏版本:",
    "Hibernation Progress": "休眠进度",
    "Import from Code": "从代码导入",
    "Import from File": "从文件导入",
    "Import your colony data:": "导入你的蚁群数据：",
    "Install Colony App": "安装蚁群App",
    "Install Idle Ant Farm as an app on your device for the best experience!": "在您的设备上安装放置蚂蚁农场作为应用程序，以获得最佳体验！",
    "Load Colony": "负载蚁群",
    "Paste code:": "粘贴代码:",
    "Pheromone Trail Preservation": "信息素轨迹保存",
    "Reset Colony": "重置蚁群",
    "Save Colony": "保存蚁群",
    "Select \"Add to Home Screen\" or \"Install\"": "选择“添加到主屏幕”或“安装”。",
    "Select file:": "选择文件:",
    "Show Installation Help": "显示安装帮助",
    "Show popup notifications when achievements are unlocked": "当成就解锁时显示弹出通知",
    "Show popup with details when the game is updated": "当游戏更新时显示弹出的详细信息",
    "Tap the share/menu button in your browser": "点击浏览器中的共享/菜单按钮",
    "This will completely reset your colony progress. This action cannot be undone.": "这将完全重置你的蚁群进度。此操作不能撤消。",
    "To install this app on your device:": "要在您的设备上安装此应用程序：",
    "Toggle between light and dark theme": "在浅色和深色主题之间切换",
    "Total Ticks:": "总Tick数：",
    "Update Announcements": "更新公告",
    "Install App": "安装App",
    "Yes, Reset": "确认，重置",
    "Are you sure you want to reset your colony?": "你确定要重置你的蚁群吗？",
    "A common worker ant. Slightly tougher than training bugs.": "一只普通的工蚁。比训练虫子稍微难一点",
    "A never-ending army of ants.": "一支永不停歇的蚂蚁大军。",
    "A new Training Bug appears with 100 health!": "一个新的训练虫子出现，生命值为100！",
    "A powerful soldier ant. Much tougher than worker ants.": "一只强大的兵蚁。比工蚁顽强多了。",
    "A relentless horde of ants.": "一群无情的蚂蚁。",
    "A weak bug used for training. Perfect for beginners.": "一种用于训练的弱小虫子。非常适合初学者。",
    "Active": "主动",
    "Active Combat": "主动作战",
    "Adventure Map": "冒险地图",
    "Adventure Progress": "冒险进度",
    "Adventure state loaded": "冒险状态已加载",
    "Annoying and surprisingly durable.": "令人讨厌，但出奇的耐用。",
    "Apocalyptic Termites": "末日白蚁",
    "Army Ant": "行军蚁",
    "Attack Damage": "攻击伤害",
    "Auto Advance (One Hit)": "自动前进（一击）",
    "Beetle": "甲虫",
    "Beetle Shell Shield": "甲虫壳护盾",
    "Big pincers, bigger stinger.": "大钳子，大毒刺。",
    "Bigger. Stronger. Shinier.": "更大。更强。更闪亮。",
    "Brighter than the sun, dangerous too.": "比太阳还亮，也很危险。",
    "Burns everything in its path.": "它会烧毁所到之处的一切。",
    "Can Kill": "可以杀死",
    "Capable of reducing everything to dust.": "能将一切化为尘埃。",
    "Close": "关闭",
    "Cockroach": "蟑螂",
    "Colossal Cockroach": "巨型蟑螂",
    "Combat": "战斗",
    "Combat Analysis": "战斗分析",
    "Combat is turn-based. Your damage scales with your ant count!": "战斗是回合制的。你的伤害取决于你的蚂蚁数量！",
    "Combat Log": "战斗日志",
    "Combat Stats": "战斗统计",
    "Controls an entire hive of wasps.": "控制整个蜂巢的黄蜂。",
    "Damage": "伤害",
    "Damage Taken/Hit:": "受到的伤害/命中：",
    "Damage:": "伤害:",
    "Dead": "死亡",
    "Defense": "防御",
    "Defense:": "防御:",
    "Destroys everything it touches.": "摧毁它所接触到的一切。",
    "Dismiss": "解散",
    "Endless Ant Swarm": "无尽的蚁群",
    "Enemy Health": "敌人生命值",
    "Essence Reward": "精华奖励",
    "Essence Reward:": "精华奖励：",
    "Even harder to kill than before.": "比以前更难杀死。",
    "Exists in multiple places at once.": "同时存在于多个地方。",
    "Faster and angrier than a hornet!": "比大黄蜂更快更愤怒！",
    "Fight": "战斗",
    "Filters:": "过滤器:",
    "Fire Ant": "火蚁",
    "Fluffy but terrifying.": "毛茸茸的，但很可怕。",
    "Food Reward": "食物奖励",
    "Food Reward:": "食物奖励:",
    "Galactic Moth": "银河飞蛾",
    "Giant Firefly": "巨型萤火虫",
    "Giant Moth": "巨蛾",
    "Giant Stag Beetle": "金龟子",
    "Grasshopper": "蚱蜢",
    "Hard shell, strong bite.": "外壳坚硬，咬合力强。",
    "Health": "生命值",
    "Health Regen": "生命回复",
    "Health:": "生命值：",
    "Housefly": "家蝇",
    "In Combat": "战斗中",
    "It seeks the biggest, brightest lights in the universe.": "它寻找宇宙中最大最亮的光。",
    "Jumps around and avoids attacks!": "跳来跳去，躲避攻击！",
    "Ladybug": "瓢虫",
    "Looks cute but can be surprisingly tough!": "看起来很可爱，但却出奇的强硬！",
    "Loves lights. Too bad it's also huge.": "喜欢灯光。可惜的是它也太大了。",
    "Massive pincers that can crush anything.": "巨大的钳子可以碾碎任何东西。",
    "Mosquito": "蚊子",
    "Mutant Fly": "变异苍蝇",
    "Not the kind that gives you superpowers.": "不是那种能让你拥有超能力的。",
    "Offline Progress Applied": "离线进度应用",
    "One Hit Only": "仅一击击杀",
    "Pebble Hammer": "卵石锤",
    "Player Stats": "玩家数据",
    "Quantum Beetle": "量子甲虫",
    "Queen Wasp": "蜂后",
    "Radioactive Spider": "放射性蜘蛛",
    "Reinforced Mandibles": "强化下颚",
    "Resin Helmet": "树脂头盔",
    "Scorpion": "蝎子",
    "Shop": "商店",
    "Show All": "显示所有",
    "Show Less": "显示更少",
    "Small but extremely irritating.": "虽然小，但非常烦人。",
    "Soldier Ant": "兵蚁",
    "Somehow even more annoying than a normal fly.": "不知怎么的，比普通苍蝇还烦人。",
    "Stag Beetle Swarm": "鹿角虫群",
    "Status": "状态",
    "Survivability:": "生存能力:",
    "Survivor of everything. Just won't die.": "万物的幸存者。就是死不了。",
    "Tarantula": "狼蛛",
    "Termite": "白蚁",
    "Thorn Spear": "刺矛",
    "Time to Kill:": "击杀时间：",
    "To change enemies, select a different bug from the Adventure Map below.": "要改变敌人，请从下面的冒险地图中选择一个不同的虫子。",
    "Too many beetles to count.": "甲虫太多了，数不过来。",
    "Training Bug": "训练虫子",
    "Ultra Beetle": "超级甲虫",
    "Wasp": "黄蜂",
    "While you were away for 16 seconds, your colony continued to work!": "你离开了16秒，你的蚁群还在继续工作！",
    "Worker Armor": "工蚁盔甲",
    "Worker Sword": "工蚁之剑",
    "You died! Returning to safe training...": "你挂了! 返回以安全训练...",
    "Actions": "行动",
    "Available Essence": "可用精华",
    "Click to browse items": "点击浏览物品",
    "Empty Slot": "空槽",
    "Equipment": "装备",
    "Equipment Stats": "装备统计",
    "Filter Items": "筛选物品",
    "Higher-level enemies provide more essence. Defeat tougher bugs to collect more!": "更高等级的敌人提供更多的精华。打败更难的虫子收集更多！",
    "Locked Slot": "未解锁栏位",
    "Merge Items": "合并物品",
    "Pheromone Essence is collected from defeated enemies in the Adventure mode.": "信息素精华是在冒险模式中从击败的敌人那里收集的。",
    "Pheromone Essence Shop": "信息素精华商店",
    "Pheromone Essence will be used to craft and upgrade items in a future update.": "信息素精华将在未来的更新中用于制作和升级物品。",
    "Power (High to Low)": "战力（从高到低）",
    "Power (Low to High)": "战力（从低到高）",
    "Quality (High to Low)": "品质（从高到低）",
    "Quality (Low to High)": "品质（从低到高）",
    "Quantity (High to Low)": "数量（从高到低）",
    "Quantity (Low to High)": "数量（从低到高）",
    "Rarity (High to Low)": "稀有性（从高到低）",
    "Rarity (Low to High)": "稀有性（从低到高）",
    "Refresh Equipment Slots": "刷新装备栏位",
    "Regen": "回复",
    "Select an item from your inventory to equip in this slot.": "从你的库存中选择一个物品装备到这个槽位中。",
    "Select Item to Equip": "选择要装备的物品",
    "slots used": "槽位使用情况",
    "Soon you'll be able to spend your Pheromone Essence on powerful upgrades and bonuses!": "很快，信息素精华就可以用于强大的升级和加成了！",
    "The Colony Alchemists are working on new formulations...": "蚁群的炼金术士正在研究新的配方……",
    "Unlock via Evolution": "通过进化解锁",
    "Work in Progress": "工作进行中",
    "Your progress will reset, but your evolutionary adaptations will remain.": "你的进度将会重置，但你的进化改造将会保留。",
    "# Changelog": "# 更新日志",
    "Calculation complete! Your colony has been updated.": "计算完毕！你的蚁群已更新。",
    "Reset filters": "重置过滤器",
    "Resource Synergy": "资源协同",
    "Resource Champion": "资源冠军",
    "Rewards": "奖励",
    "Rewards:": "奖励:",
    "Risky": "有风险",
    "Safe": "安全",
    "Sort by:": "排序方式:",
    "Start Quest": "开始任务",
    "Skip Calculation": "跳过计算",
    "Show All Items": "显示全部物品",
    "Max Level:": "最高等级:",
    "Loading changelog...": "加载更新日志...",
    "Infinity Shard": "无限碎片",
    "Bugs": "虫子",
    "Level": "等级",
    "Rare Items": "稀有物品",
    "Legendary Items": "传说物品",
    "Legendary": "传说",
    "Rare": "稀有",
    "Quests": "任务",
    "Fixed": "修复",
    "Game Wiki": "游戏Wiki",
    "Generators": "生成器",
    "Genesis Claw": "创世之爪",
    "global": "全局",
    "Global Multiplier": "全局乘数",
    "Sweet Scent": "香甜的味道",
    "Swarm Lord": "虫群领主",
    "Removed": "移除",
    "Refresh Statistics": "刷新统计",
    "Hide Production Summary": "隐藏生产统计",
    "Show Production Summary": "显示生产统计",
    "We're calculating the progress made during this time.": "我们正在计算这段时间取得的游戏进度。",
    "Food Generated": "生成的食物",
    "A basic sword for training. Better than nothing!": "聊胜于无！",
    "A crown forged from the essence of ant queens, granting supreme authority.": "用蚁后的精华铸造的王冠，授予至高无上的权威。",
    "A deadly dagger coated with scorpion venom that melts through defenses.": "一把涂有蝎子毒液的致命匕首，可以穿透防御。",
    "A divine artifact that amplifies productivity to godlike levels.": "神器，能将生产力提升至神级。",
    "A divine core of pure evolutionary essence.": "一个神圣的纯粹的进化精华的核心。",
    "A fearsome weapon forged from the mandibles of giant beetles.": "由巨型甲虫的下颌骨制成的可怕武器。",
    "A fragment of the universe's beginning.": "宇宙起源的碎片。",
    "A helm that enhances tactical thinking and ant coordination.": "增强战术思维和蚂蚁配合能力的头盔。",
    "A helmet crafted from hardened tree resin, offering good protection.": "由硬化树脂制成的头盔，提供良好的保护。",
    "A mysterious crystal that resonates with evolutionary energy, enhancing EP gains.": "一种神秘的晶体，与进化能量共振，增强EP增益。",
    "A mystical device that allows control over vast swarms of insects.": "一种可以控制大量昆虫的神秘装置。",
    "A mythical blade that tears through the fabric of reality.": "一把能撕裂现实的神话之刃。",
    "A mythical catalyst that exponentially increases productivity.": "一种神奇的催化剂，可以成倍地提高生产力。",
    "A mythical matrix of pure evolutionary potential.": "具有纯粹进化潜力的神话矩阵。",
    "A powerful artifact that amplifies the productivity of the entire colony.": "一个强大的神器，可以放大整个蚁群的生产力。",
    "A shield made from a small beetle's shell. Surprisingly durable.": "用小甲虫的壳做成的盾牌。令人惊讶的是耐用。",
    "A simple cloak made from leaves that provides minimal protection.": "一种由树叶制成的简单斗篷，提供的保护最少。",
    "A simple wooden shield that offers basic protection.": "一个简单的木制盾牌，提供基本的保护。",
    "A small pebble attached to a stick. Crude but effective.": "附着在棍子上的小卵石。粗暴但有效。",
    "A spear tipped with a sharp rose thorn. Excellent for piercing.": "尖刺矛尖有尖锐的玫瑰刺的矛非常适合穿洞。",
    "A sturdy sword used by worker ants.": "工蚁使用的坚固的剑。",
    "A weapon that contains the power of creation itself.": "一件拥有创造之力的武器。",
    "Ant Commander Armor": "蚂蚁指挥官盔甲",
    "Ant Queen Crown": "蚂蚁蚁后王冠",
    "Ant Scout Gear": "蚂蚁侦察装备",
    "Ant Tactician Helm": "蚂蚁战术头盔",
    "Ant Training Kit": "蚂蚁训练套装",
    "Armor crafted from the hardened exoskeleton of a giant stag beetle.": "盔甲是由一只巨大的雄鹿甲虫坚硬的外骨骼制成的。",
    "Armor that manipulates time itself, allowing the wearer to exist slightly out of phase with reality.": "操纵时间的盔甲，允许穿戴者存在于与现实相异的地方。",
    "Armor that marks you as a supreme commander of ant armies.": "盔甲，标志着你是蚂蚁军队的最高指挥官。",
    "Armor woven from the threads of eternity itself.": "由永恒之线编织而成的盔甲。",
    "Ascension Matrix": "转生矩阵",
    "Basic protective gear for training.": "训练用基本防护装备。",
    "Basic tools that help ants gather resources more efficiently.": "帮助蚂蚁更有效地收集资源的基本工具。",
    "Basic training equipment for young ants.": "你蚂蚁的基础训练装备",
    "Bugs & Drops": "虫子 & 掉落",
    "Chronos Shell": "时空之壳",
    "Common": "普通",
    "Common Items": "普通道具",
    "Divine": "神圣",
    "Divine Items": "神圣物品",
    "Durable armor worn by worker ants.": "工蚁穿的耐久的盔甲。",
    "Entropy Fangs": "熵牙",
    "Epic": "史诗",
    "Epic Items": "史诗物品",
    "Eternity Weave": "永恒编织",
    "Evolution Crystal": "进化水晶",
    "Exoskeleton Plate": "外骨骼板",
    "Filter by Rarity": "按稀有性筛选",
    "Hive Amplifier": "蚁穴放大器",
    "Items": "物品",
    "Lightweight gear perfect for ant scouts.": "轻巧的装备非常适合蚂蚁侦察兵。",
    "Mandible Crusher": "下颌骨破碎机",
    "Mandibles that accelerate entropy in whatever they touch.": "下颚能使接触到的任何东西的熵增加。",
    "Mandibles that exist in multiple dimensions at once.": "同时存在于多个维度的下颌骨。",
    "Mythic": "神话",
    "Mythic Items": "神话物品",
    "Pheromone Shop": "信息素商店",
    "Prestige Upgrades": "声望升级",
    "Strengthened mandibles that can cut through tougher materials.": "更坚固的下颌骨可以切割更坚硬的材料。",
    "Uncommon": "罕见",
    "Uncommon Items": "罕见物品",
    "All Generators": "所有生成器",
    "Ant Legion Commander": "蚂蚁军团指挥官",
    "Ant Queen Guardian": "蚂蚁蚁后守护者",
    "Ant Scout Master": "蚂蚁侦察员",
    "Ant Tactician": "蚂蚁战术家",
    "Ant Training Master": "蚂蚁训练大师",
    "Antopolis": "Antopolis",
    "Basic Information": "基本信息",
    "Bugs that drop this item": "掉落这个物品的虫子",
    "Production Modifiers": "生产词缀",
    "Rarity:": "稀有度：",
    "Regeneration": "回复",
    "Special Effects": "特殊效果",
    "Type:": "类型:",
    "Hivemind": "蚁穴思维",
    "ep:": "进化点数:",
    "For the optimal evolution, focus on maximizing food production, colony level, and unlocking adaptations to earn more EP. Remember that early evolutions may feel slower, but each evolution makes subsequent ones faster and more rewarding.": "对于最优进化，关注最大限度地提高食物产量，蚁群等级，并解锁适应以获得更多的进化点数。记住，早期的进化可能会让人感觉更慢，但每次进化都会让随后的进化更快、更有意义。",
    "About Metamorphosis": "关于蜕变",
    "Adaptations and specialization levels": "改造和专精等级",
    "All resources (food, minerals, etc.)": "所有资源（食物，矿物等）",
    "Auto Salvage": "自动回收",
    "Boosts worker ants by 5%, nurseries by 2.5%, and EP gain by 20% per level": "每升一级增加工蚁5%，苗圃2.5%，EP增加20%",
    "Colony level and title": "蚁群等级和头衔",
    "Colony Rush": "蚁群冲锋",
    "Each evolution unlocks new technologies, ant types, and game mechanics.": "每次进化都会开启新的技术、蚂蚁类型和游戏机制。",
    "Evolution Points (EP) and all bonuses from them": "进化点数（EP）及其所有奖励",
    "Evolving resets most of your progress, including resources, structures, adaptations, and more.": "进化重置了你的大部分进度，包括资源、结构、改造等等。",
    "Exponential Pheromone": "指数信息素",
    "is your colony's method of evolution, allowing you to transform your ants into more advanced forms and gain powerful permanent bonuses.": "是你的蚁群的进化方法，允许你将你的蚂蚁变成更高级的形式，并获得强大的永久奖励。",
    "Level-requirement": "等级要求",
    "Metamorphosis Process:": "蜕变过程：",
    "No upgrades match your filters": "没有符合筛选条件的升级",
    "Nursery Advancement": "苗圃进阶",
    "nursery:": "苗圃：",
    "Pheromone production increases exponentially per level": "信息素的产量呈指数级增长",
    "pheromone:": "信息素:",
    "Premium items and pets": "付费道具和宠物",
    "Purchased structures and their levels": "购买的建筑及其等级",
    "Queen Chamber Advancement": "蚁后室进阶",
    "Reduces nursery level-up requirements by 20% per level": "每级降低苗圃升级需求20%",
    "Reduces queen chamber level-up requirements by 20% per level": "每级降低20%的蚁后室升级要求",
    "Reduces the requirements for all generator level-ups by 10% per level": "每升一级减少10%的生成器升级需求",
    "Reduces worker level-up requirements by 15% per level": "每升一级减少15%的工蚁升级要求",
    "Research and technology": "研究与技术",
    "Swift Progression": "迅速发展",
    "Unlock the Colony Rush ability, allowing you to skip ahead 30 seconds of production time. Limited to 50 uses per day with a cooldown period between uses.": "解锁蚁群冲锋技能，让你提前30秒生产时间。每天限制使用50次，每次使用之间有冷却时间。",
    "Unlocked achievements": "解锁成就",
    "What Resets:": "重置:",
    "What You Keep:": "你保留的东西：",
    "Worker Advancement": "工蚁进阶",
    "worker:": "工蚁：",
    "You'll gain EP based on your progress in the current evolution.": "你将根据当前进化的进度获得进化点数。",
    "You'll keep all EP (Evolution Points) and the bonuses they provide.": "你将保留所有EP（进化点数）及其提供的奖励。",
    "Levels up based on foraging ticks in current evolution": "根据当前进化中的觅食Tick来升级",
    "epic": "史诗",
    "EP Boost": "EP提升",
    "Equip": "装备",
    "Equipment Boost": "装备提升",
    "damage reduction": "伤害减免",
    "Merge All": "合并全部",
    "legendary": "传说",
    "divine": "神圣",
    "common": "普通",
    "Collect": "收集",
    "mythic": "神话",
    "per second": "每秒",
    "rare": "稀有",
    "Salvage": "回收",
    "Nursery Production": "蚁群生产",
    "Queen Production": "蚁后生产",
    "Purchase Upgrade": "购买升级",
    "Total Damage": "总伤害",
    "Total Health": "总生命值",
    "Total Regen": "总回复",
    "Total Combat Stats": "总战斗属性",
    "Stats:": "属性:",
    "uncommon": "罕见",
    "Merge Item": "合并物品",
    "Merged Item": "已合并物品",
    "Farm Production": "农场生产",
    "Item Filter Settings": "物品过滤器设置",
    "Salvage Information:": "回收信息",
    "Merge Information:": "合并信息",
    "Production Modifiers:": "生产词缀:",
    "Configure which items your colony should collect. Items marked as \"Filtered\" will be automatically discarded when dropped. This is useful for preventing your inventory from filling up with lower-tier items as you progress.": "配置你的蚁群应该收集哪些物品。标记为“已过滤”的项目将在丢弃时自动丢弃。这对于防止你的库存在你的进程中被低级物品填满是很有用的。",
    "Auto-Salvage Filtered Items": "自动回收过滤项目",
    "Configure which items to collect or filter out.": "配置要收集或过滤掉的物品。",
    "Continue merging to higher levels when possible": "在可能的情况下继续合并到更高的等级",
    "Each merge level provides:": "每个合并等级提供：",
    "Higher rarity and merge level items yield more essence": "更高的稀有度和合并等级的物品产生更多的精华",
    "Salvaging this item will yield:": "回收这个物品将产生：",
    "Worker Production": "工蚁生产",
    "Click to unequip": "点击卸下",
    "equipment": "装备",
    "Equipped": "已装备",
    "nursery": "蚁群",
    "Merged Items": "已合并物品",
    "Production Bonuses": "生产加成",
    "worker": "工蚁",
    "Confirm Salvage": "确认回收",
    "Unequip": "卸下",
    "Confirm Merge": "确认合并",
    "No more items can be merged.": "没有更多的物品可以合并。",
    "Current Progress": "当前进度",
    "Locked Equipment Slot": "锁定的装备槽位",
    "This equipment slot is currently locked. You can unlock additional equipment slots through the prestige upgrade \"Equipment Mastery\".": "该装备槽位未解锁。你可以通过声望升级\“装备精通\”解锁额外的装备槽位。",
    "Tip: Each level of Equipment Mastery unlocks one additional slot, up to a maximum of 10 bonus slots.": "提示：每升一级装备精通解锁一个额外槽位，最多10个奖励槽位。",
    "Food:": "食物:",
    "HP:": "生命值:",
    "hits": "命中",
    "You survive:": "你幸存:",
    "You take:": "你受到:",
    "DEF:": "防御:",
    "DMG:": "伤害:",
    "Available": "可用",
    "Available Quests": "可用任务",
    "Basic Training": "基础训练",
    "Bug Slayer Initiate": "虫子杀手入门",
    "Attack": "攻击",
    "Ant Terminator": "蚂蚁终结者",
    "Alive": "生存",
    "Army Ant Annihilation": "行军蚁歼灭",
    "Collect Pheromone": "收集信息素",
    "Auto Advance (One Hit Kills)": "自动冒险（一击击杀）",
    "Beetle Buster": "甲虫克星",
    "Beetle Genocide": "甲虫种族灭绝",
    "Dangerous": "危险",
    "Cosmic Food Harvester": "宇宙食物收割机",
    "Colony Provisions": "蚁群补给",
    "Essence:": "精华:",
    "Collect 1,000,000 food for a colony-wide celebration.": "为整个蚁群的庆祝活动收集100万份食物。",
    "Collect 1,000,000 pheromone essence to achieve grandmaster status.": "收集100万信息素精华达到特级大师级别",
    "Collect 1,000,000,000 food to join the elite of food collectors.": "收集10亿份食物，加入食物收集者的精英。",
    "Collect 1,000,000,000,000 food to become a legend among food collectors.": "收集1000,000,000,000个食物，成为食物收集者中的传奇。",
    "Collect 10,000,000 food to establish your colony as a food powerhouse.": "收集1000万食物来建立你的蚁群作为一个食物发电站。",
    "Collect 10,000,000 pheromone essence to transcend mortal limitations.": "收集1000万信息素精华，超越人类极限。",
    "Collect 100,000 pheromone essence to master the mystical arts.": "收集10万信息素精华掌握神秘艺术。",
    "Collect 100,000,000 food to become a food industry mogul.": "收集1亿份食物，成为食物工业大亨。",
    "Collect 15,000 pheromone essence to reshape the destiny of your colony.": "收集15000个信息素精华来重塑你的蚁群的命运。",
    "Collect 1e15 pheromone essence to unlock the secrets of the universe.": "收集1e15个信息素精华来解开宇宙的秘密。",
    "Collect 1e20 food to feed the entire universe.": "收集1e20种食物来养活整个宇宙。",
    "Collect 2,000 pheromone essence to enhance your colony's powers.": "收集2000个信息素精华来增强你的蚁群的力量。",
    "Collect 250,000 food to prepare for harsher seasons.": "收集25万份食物为更严酷的季节做准备。",
    "Collect 5,000 pheromone essence to reach new heights of power.": "收集5000信息素精华达到新的高度的力量。",
    "Collect 5,000,000 food and 100,000 pheromone essence simultaneously.": "同时收集500万食物和10万信息素精华。",
    "Collect 50,000 food to support your growing colony.": "收集5万食物来支持你不断增长的蚁群。",
    "Collect 50,000,000 food and 1,000,000 pheromone essence simultaneously.": "同时收集5000万个食物和100万个信息素精华。",
    "Collect 500 pheromone essence to unlock new mystical powers.": "收集500信息素精华解锁新的神秘力量。",
    "Collect 500,000 food and 1,000 pheromone essence to prove your mastery of resources.": "收集50万食物和1000个信息素精华来证明你对资源的掌握。",
    "Defeat 1,000 army ants to prove your colony's supremacy.": "击败1000只军蚁来证明你的蚁群的霸权。",
    "Defeat 1,000 bugs of any type to advance your extermination skills.": "击败1000个任何类型的虫子来提升你的消灭技能。",
    "Defeat 10 tarantulas to prove your colony's strength.": "击败10只狼蛛来证明你的蚁群的实力。",
    "Defeat 10,000 bugs of any type to become a legend among exterminators.": "击败1万只任何类型的虫子，成为灭虫者中的传奇人物。",
    "Defeat 100 bugs of any type to begin your career as an exterminator.": "击败100个任何类型的虫子，开始你的职业生涯作为一个灭虫者。",
    "Defeat 100 quantum beetles to harness their reality-bending power.": "击败100只量子甲虫，利用它们扭曲现实的能力。",
    "Defeat 100,000 bugs of any type to achieve mastery in the art of bug hunting.": "击败100000个任意类型的虫子，达到精通捕虫的境界。",
    "Defeat 15 grasshoppers to protect your colony.": "打败15只蚱蜢来保护你的蚁群。",
    "Defeat 2,500 scorpions to eliminate their threat.": "击败2500只蝎子来消除他们的威胁。",
    "Defeat 25 training bugs to practice your combat skills.": "击败25个训练虫子来练习你的战斗技能。",
    "Defeat 250 galactic moths to harness their cosmic energy.": "击败250个银河飞蛾来利用它们的宇宙能量。",
    "Defeat 3 army ants to demonstrate your colony's prowess.": "击败3只军蚁来展示你的蚁群的实力。",
    "Defeat 3,000 tarantulas to free the colony from fear.": "打败3000只狼蛛，让蚁群摆脱恐惧。",
    "Defeat 5 scorpions to secure your colony's dominance.": "击败5只蝎子以确保蚁群的统治地位。",
    "Defeat 5,000 beetles to eliminate their threat forever.": "打败5000只甲虫，永远消灭它们的威胁。",
    "Defeat 50 bugs of any type to begin your path as a bug slayer.": "击败50个任何类型的虫子，开始你的道路作为一个虫子杀手。",
    "Defeat 500 endless ant swarms to claim ultimate hive dominance.": "击败500个无尽的蚁群，以获得最终的蚁穴统治权。",
    "Defeat 8 beetles to claim their territory.": "击败8只甲虫，占领它们的领地。",
    "Defeat a total of 1,000,000 bugs of any type to become the ultimate predator.": "击败总共1,000,000只任何类型的虫子，成为终极捕食者。",
    "Endless Swarm Challenge": "无尽的蚁群挑战",
    "Essence Architect": "精华上师",
    "Essence Collector": "精华收集器",
    "Essence Grandmaster": "精华特级大师",
    "Essence Harvester": "精华收割机",
    "Essence Master": "精华大师",
    "Essence Transcendent": "精华超越",
    "Essence Virtuoso": "精华大师",
    "Exterminator Adept": "灭虫高手",
    "Exterminator Expert": "灭虫专家",
    "Exterminator Master": "灭虫大师",
    "Exterminator Novice": "灭虫新手",
    "Extreme Bug Hunter": "极限猎虫者",
    "Feast Preparation": "宴会准备",
    "Food Billionaire": "食物的亿万富翁",
    "Food Trillionaire": "食物万亿富翁",
    "Food Tycoon": "食物大亨",
    "Galactic Moth Hunter": "银河飞蛾猎手",
    "Grasshopper Hunter": "蚱蜢猎手",
    "Multiple Goals": "多重目标",
    "Pheromone Transcendence": "信息素超越",
    "Quantum Beetle Hunter": "量子甲虫猎人",
    "Safe to Fight": "安全作战",
    "Scorpion Slaughter": "蝎子屠杀",
    "Scorpion Subjugator": "蝎子征服者",
    "Spider Slayer": "蜘蛛杀手",
    "Supreme Resource Master": "至尊资源大师",
    "Tarantula Terror": "狼蛛恐怖",
    "Too Strong": "太强了",
    "Universal Harvester": "万能收割机",
    "Winter Storage": "冬季贮藏",
    "You deal:": "你造成了:",
    "You survive:": "你存活：",
    "Name": "名称",
    "Price": "价格",
    "A sweet pheromone blend that makes all ants work more efficiently.": "一种甜蜜的信息素混合物，使所有蚂蚁的工作效率更高。",
    "Accelerates evolutionary progress through pheromone enhancement.": "通过信息素增强加速进化进程。",
    "Ant Trail Blazer": "蚂蚁开拓者",
    "Ant-i-Gravity": "反重力",
    "ANTstronaut Program": "宇航员计划",
    "Defying the laws of physics, just like ants carrying 50x their weight!": "无视物理定律，就像蚂蚁背负着50倍于自己体重的重量！",
    "Enhances food production through advanced pheromone manipulation.": "通过先进的信息素操纵提高粮食产量。",
    "Evolution Catalyst": "进化催化剂",
    "Food Amplifier": "食物放大器",
    "Formic Boost": "蚁群加成",
    "Formicidable Power": "杀敌之力",
    "Harness the power of formic acid to supercharge your colony.": "利用甲酸的力量给你的蚁群充电。",
    "Hill of a Deal": "交易之山",
    "Mark your path to success with powerful pheromone trails.": "用强大的信息素标记你的成功之路。",
    "Max Level": "最高等级",
    "Mystery enhancement": "神秘增强",
    "No Pic-ant": "未选蚂蚁",
    "One small step for ant, one giant leap for ant-kind!": "蚂蚁的一小步，蚁族的一大步！",
    "This deal is too good to pass up! Trust me, I'm an antrepreneur.": "这个交易太好了，不容错过！相信我，我是个企业家。",
    "Collect 5,000 Pheromone Essence total": "总共收集5000个信息素精华",
    "Reach level 10 with Evolution Catalyst": "使用进化催化剂达到10级",
    "Reach level 10 with Sweet Scent": "达到10级甜香味",
    "Reach level 15 with Ant-i-Gravity": "使用反重力达到15级",
    "Reach level 20 with No Pic-ant": "在没有蚂蚁的情况下升到20级",
    "Reach level 25 with Formicidable Power": "杀敌之力等级达到25级",
    "Reach level 5 with Ant Trail Blazer": "使用蚂蚁开拓者升到5级",
    "Reach level 5 with Food Amplifier": "使用食物放大器达到5级",
    "Reach level 50 with Hill of a Deal": "交易之山等级达到50级",
    "Uncl-Ant Power": "蚁叔之力",
    "Unleash the formidable power of the Formicidae family!": "释放蚁科家族强大的力量！",
    "Unlock": "解锁",
    "Unlocked Status": "解锁状态",
    "Upgrade": "升级",
    "Upgrade existing items to discover new pheromone enhancements!": "升级现有的项目，以发现新的信息素增强！",
    "We packed the perfect pheromones for this pic-ant! Spicy!": "我们为这只蚂蚁准备了完美的信息素！辣！",
    "With great power comes great respANTsibility.": "能力越大，责任越大。",
    "A new Giant Stag Beetle appears with 1.00e+65 health!": "一个新的巨大的雄鹿甲虫出现，有1.00e+65生命值！",
    "A new Worker Ant appears with 500 health!": "一个新的工蚁出现了，有500点生命值！",
    "Abandon Quest": "放弃任务",
    "Active Quest": "主动任务",
    "Complete Active Quest First": "先完成主动任务",
    "In Progress": "进行中",
    "Bugs Progress": "虫子进度",
    "Switching target from Giant Stag Beetle to Training Bug": "将目标从雄鹿甲虫切换到训练虫",
    "Switching target from Training Bug to Giant Stag Beetle": "将目标从训练虫切换到巨鹿甲虫",
    "Switching target from Training Bug to Worker Ant": "目标从训练虫切换到工蚁",
    "Quest": "任务",
    "Quest Target": "任务目标",
    "worker ants": "工蚁",
    "Pheromone Essence": "信息素精华",
    "Warning: Inventory Full": "警告: 库存已满",
    "You cannot unequip this item because your inventory is full. Free up space first.": "你不能解除装备这个物品，因为你的库存已经满了。请先释放空间。",
    "All equipment slots are occupied. Select which item you want to replace with": "所有装备槽位已被占用,请选择要替换的物品",
    "One Hit Kill": "一击击杀",
    "Click to replace": "点击以替换",
    "Inventory Full Warning": "库存已满警告",
    "Select Slot to Replace": "选择槽位以替换",
    "Your inventory is full! If you replace an equipped item, it may be discarded as there's no space to store it. Consider freeing up space first.": "你的库存已经满了！如果你更换装备的物品，它可能会被丢弃，因为没有空间来储存它。首先考虑腾出空间。",
    "All production increases by 2x per level": "每升一级所有产量增加2x",
    "Evolution": "进化",
    "Boosts food production by 12%, pheromone production by 10% per level": "每级增加12%的粮食产量，10%的信息素产量",
    "Divides the cost of nurseries by 8200 per level": "苗圃成本除以8200每级",
    "Doubles the amount of Evolution Points gained per cycle": "使每个周期获得的进化点数翻倍",
    "Efficient Queens": "高效蚁后",
    "Each evolution cycle grants a stacking 1% bonus to food production": "每个进化周期给予食物生产1%的叠加加成",
    "Evolutionary Adaptation": "进化改造",
    "Exponential Growth": "指数成长",
    "food:": "食物:",
    "Mega Colony": "超级蚁群",
    "Nursery Cost Discount": "苗圃成本折扣",
    "Queens produce 15% more nurseries per level": "蚁后每级增加15%的苗圃产量",
    "Unlocks the Mega Colony generator": "解锁超级蚁群生成器",
    "Kill": "击杀",
    "Effect": "效果",
    "colony:": "蚁群:",
    "global:": "全局:",
    "megacolony:": "超级蚁群:",
    "Advanced Efficient Queens": "高级高效蚁后",
    "Advanced Food Processing": "高级食品加工",
    "Advanced Generator Advancement": "高级生成器进阶",
    "Advanced Tier Integration": "高级层集成",
    "Antopolis has a 1% chance per level to reproduce itself each tick (max 5%)": "Antopolis每升一级有1%的几率复制自己（最多5%）",
    "Antopolis Self-Replication": "Antopolis自我复制",
    "Bonus from Evolution Mastery upgrade.": "进化精通升级奖励。",
    "Boosts all production by 5%, EP gain by 25%": "提高所有产量5%，EP增益25%",
    "Boosts mega colonies by 10%, hive minds by 7%, and doubles EP gain per level": "增加10%的超级蚁群，7%的蜂群思维，每级增加一倍的EP",
    "Boosts pheromone production by 10% per level (multiplier) and adds 25% to the amount of pheromone produced per level": "每级增加10%的信息素产量（乘数），每级增加25%的信息素产量",
    "Boosts queen chambers by 8%, colonies by 5%, and pheromone production by 15% per level": "每级提高蚁后室8%，蚁群5%，信息素产量15%",
    "Boosts queen reproduction by 15%, nursery efficiency by 10%, and reduces all ant costs by 5% per level": "每升一级提高蚁后繁殖率15%，苗圃效率10%，降低所有蚂蚁消耗5%",
    "Colonies have a 1% chance per level to reproduce themselves each tick (max 5%)": "菌落每级有1%的机会繁殖自己（最多5%）",
    "Colonies produce 30% more queen chambers per level": "每升一级，蜂群生产的蚁后室增加30%",
    "Colony Expansion Tactics": "蚁群扩张策略",
    "Colony Self-Replication": "蚁群自我复制",
    "Divides the cost of queen chambers by 1e6 per level": "每级将蚁后室的费用除以1e6",
    "Equipment Mastery": "装备精通",
    "Exponential Evolution": "指数进化",
    "Extended Rush": "延长冲锋",
    "Grand Colony Synergy": "大型蚁群协同",
    "Hive Mind Self-Replication": "蚁穴思维自我复制",
    "Hive Minds have a 1% chance per level to reproduce themselves each tick (max 5%)": "蚁穴思维每级有1%的几率复制自己（最多5%）",
    "hivemind:": "蚁穴思维:",
    "Increases Colony Rush duration by 10 seconds per level.": "每升一级增加蚁群冲锋持续时间10秒。",
    "Increases Evolution Points gained per cycle exponentially": "以指数方式增加每个周期获得的进化点",
    "Increases food production by 20% per level": "每升一级增加20%的粮食产量",
    "Increases maximum Colony Rushes per day by 2 per level.": "每级增加每天2点的最大蜂群冲锋。",
    "Increases the chance to get a double kill in adventure mode, giving you a better chance to get the items you want.": "增加在冒险模式中获得双杀的机会，让你有更好的机会获得你想要的物品。",
    "Increases the chance to re-roll items from defeated bugs in adventure mode, giving you a better chance to get the items you want.": "提升冒险模式中从被击败的虫子身上重新掷出物品的概率，让你更容易获得想要的物品。",
    "Increases the effect of the double kill in adventure mode, increases the quantity of bugs killed in a double kill.": "增加冒险模式中双杀的效果，增加双杀中杀死的虫子数量。",
    "Mega Colonies have a 1% chance per level to reproduce themselves each tick (max 5%)": "超级蜂群每级有1%的几率繁殖自己（最多5%）",
    "Mega Colonies produce 40% more colonies per level": "超级蚁群每升一级能多生产40%的蚁群",
    "Mega Colony Optimization": "超级蚁群优化",
    "Mega Colony Self-Replication": "超级蚁群自我复制",
    "Mid-Tier Synergy": "中层协同",
    "Pheromone Synergy Multiplier": "信息素协同乘数",
    "Queen Chamber Cost Discount": "蚁后室成本折扣",
    "Queen Chamber Self-Replication": "蚁后室自复制",
    "Queen Chambers have a 1% chance per level to reproduce themselves each tick (max 5%)": "蚁后室每级有1%的机会复制自己（最多5%）",
    "queenChamber:": "蚁后室：",
    "Queens produce 30% more nurseries per level": "蚁后每等级增加30%的苗圃产量",
    "Re-Roll Chance": "重掷机会",
    "Reduces level-up requirements for high-tier generators by 25% per level": "每升一级降低高级生成器25%的升级要求",
    "Reduces the cooldown between Colony Rushes by 2 foraging trips per level.": "每升1级减少2觅食时间。",
    "Reproduction Nexus": "繁殖中枢",
    "Rush Capacity": "冲锋容量",
    "Rush Efficiency": "冲锋效率",
    "Unlock an additional equipment slot. Each level unlocks one more slot, up to a maximum of 10 slots.": "解锁一个额外的装备插槽。每级解锁1个槽位，最多解锁10个槽位。",
    "Upgrade not yet unlocked": "升级尚未解锁",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "training_sword": "training_sword",
    "void_reaver": "void_reaver",
    "beetle_shell_shield": "beetle_shell_shield",
    "divine_eternity_weave": "divine_eternity_weave",
    "divine_genesis_claw": "divine_genesis_claw",
    "divine_infinity_shard": "divine_infinity_shard",
    "evolution_crystal": "evolution_crystal",
    "exoskeleton_plate": "exoskeleton_plate",
    "leaf_cloak": "leaf_cloak",
    "Megacolony": "Megacolony",
    "mythic_catalyst": "mythic_catalyst",
    "mythic_swarm_controller": "mythic_swarm_controller",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "ID:": "ID:",
    "<h1>Opinionated, production ready template for Vite and Vue 3</h1>\n\n      <p>This site requires JavaScript to work.</p>": "<h1>为Vite和Vue 3制作的模板</h1>\n\n      <p>这个站点需要JavaScript才能工作。</p>",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Processing foraging trips: ": "处理觅食之旅: ",
    "Increases base food production of workers by ": "增加工蚁的基础食物产量 ",
    "Achievements Boost: ": "成就提升: ",
    "Item Bonus: ": "物品加成: ",
    "Effect: ": "效果: ",
    "Evolution Count: ": "进化数量: ",
    "(Unlocks at level ": "(解锁于等级 ",
    "Processing: ": "进度: ",
    "Max Level: ": "最高等级: ",
    "Generated: ": "生成: ",
    "Self-replicated: ": "自我复制: ",
    "Health: ": "生命值: ",
    "Defense: ": "防御: ",
    "Damage: ": "伤害: ",
    "Boosted: ": "提升: ",
    "Omnipotent Catalyst": "无所不能的催化剂",
    "Transcendence Core": "超越核心",
    "Universal Amplifier": "万能放大器",
    "Venom Dagger": "毒刃匕首",
    "Quantum Mandibles": "量子下颚",
    "Swarm Controller": "虫群控制器",
    "Training Armor": "训练护甲",
    "Training Sword": "训练之剑",
    "Void Reaver": "虚空掠夺者",
    "Wooden Shield": "木盾",
    "Leaf Cloak": "树叶斗篷",
    "To unlock: ": "解锁要求: ",
    "Decreases the cost of ": "降低成本对于 ",
    "Increases food production of ": "增加食物产量对于 ",
    "Produces ": "产生 ",
    "Current: ": "当前: ",
    "Merge Level ": "合并等级 ",
    "Foraging Tools": "觅食工具",
    "Double ": "双倍",
    "Automatically salvage filtered items for ": "自动回收过滤的物品对于 ",
    "Evolution Mastery: ": "进化精通：",
    "Kill ": "击杀",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "% complete": "% 完成",
    "s/trip": "秒/旅行",
    "/trip": "秒/旅行",
    " auto)": " 自动)",
    " completed": " 已完成",
    " slots unlocked)": " 槽位已解锁)",
    " Drop Table": " 掉落表",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)(.+)\/([\d\.]+)(.+)\)$/,
    /^下一个(.+)$/,
    /^解锁(.+)$/,
    /^\(解锁(.+)$/,
    /^等级(.+)$/,
    /^成本(.+)$/,
    /^Added (.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^\+([\d\.]+)K$/,
    /^\+([\d\.]+)M$/,
    /^\+([\d\.]+)B$/,
    /^\(([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^\(([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+)T \/ ([\d\.,]+)e\+([\d\.,]+)$/,
    /^([\d\.]+)B \/ ([\d\.,]+)B$/,
    /^([\d\.]+)M \/ ([\d\.,]+)M$/,
    /^([\d\.]+)K \/ ([\d\.,]+)K$/,
    /^([\d\.]+)K\/([\d\.,]+)K$/,
    /^([\d\.]+)Sp$/,
    /^([\d\.]+)Qa$/,
    /^([\d\.]+)Qi$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\)$/,
    /^([\d\.,]+) ×$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\/([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You collected (.+) Pheromone Essence!$/, '你收集了 $1 信息素精华!'],
    [/^You found (.+) wooden_shield!$/, '你找到了 $1 木盾!'],
    [/^You found (.+) hive_amplifier!$/, '你找到了 $1 蚁穴放大器!'],
    [/^You found (.+) training_sword!$/, '你找到了 $1 训练之剑!'],
    [/^You found (.+) leaf_cloak!$/, '你找到了 $1 树叶斗篷!'],
    [/^You found (.+) training_armor!$/, '你找到了 $1 训练盔甲!'],
    [/^You collected (.+) bonus Pheromone Essence \((.+) multiplier\)!$/, '你收集了 $1 奖励信息素精华（$2 乘数）！'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^A new (.+) appears with (.+) health!$/, '一只新的 $1 出现了，它有 $2 生命值！'],
    [/^Switching target from (.+) to (.+)$/, '将目标从 $1 切换到 $2'],
    [/^You defeated (.+) and gained (.+) food \((.+) of your food\/sec\)!$/, '你击败了 $1 并获得 $2 食物（相当于你食物的 $3/秒）！'],
    [/^Your equipment stats are boosted by your worker ants! Each stat is multiplied by your worker ant count \(currently (.+)\), giving you a significant combat advantage.$/, '你的装备属性被你的工蚁提升了！每个属性乘以你的工蚁数量（目前是 $1），给你一个显著的战斗优势。'],
    [/^Earn (.+) evolution points in total$/, '总计获得 $1 进化点数'],
    [/^You regenerate (.+) health \((.+) HP\)$/, '你回复了 $1 生命值（$2 生命值）'],
    [/^You deal (.+) damage to (.+) \((.+) HP\)$/, '你对 $2 造成了 $1 伤害（$3 生命值）'],
    [/^(.+) deals (.+) damage to you \((.+) HP\)$/, '$1 对你造成了 $2 伤害（$3 生命值）'],
    [/^You start fighting (.+) \((.+) damage, (.+) health\)$/, '你开始和 $1 战斗（$2 伤害，$3 生命值）'],
    [/^Your equipment provides a damage boost of (.+) \((.+) base \+ (.+) equipment boost\)$/, '你的装备提供 $1 伤害提升（$2 基础 + $2 装备提升）'],
    [/^Buy for (.+) food$/, '购买花费 $1 食物'],
    [/^Successfully performed (.+) merge operations! \((.+) at level (.+), (.+) at level (.+), (.+) at level (.+)\) Gained (.+) merge levels.$/, '成功执行了 $1 次合并操作！（$2 等级 $3，$4 等级 $5，$6 等级 $7）获得 $8 合并等级'],
    [/^Successfully performed (.+) merge operations! \((.+) at level (.+), (.+) at level (.+)\) Gained (.+) merge levels.$/, '成功执行了 $1 次合并操作！（$2 等级 $3，$4 等级 $5）获得 $6 合并等级'],
    [/^Successfully performed (.+) merge operations! Gained (.+) merge levels.$/, '成功执行了 $1 次合并操作！获得 $2 合并等级'],
    [/^Successfully performed (.+) merge operation! Gained (.+) merge levels.$/, '成功执行了 $1 次合并操作！获得 $2 合并等级'],
    [/^Successfully merged (.+) into (.+)$/, '成功合并了 $1 为 $2'],
    [/^Merge (.+) to create a (.+) version\?$/, '合并 $1 以创造一个 $2 版本？'],
    [/^This will salvage all (.+) items.$/, '这将回收全部 $1 物品。'],
    [/^Salvage (.+) for (.+) Pheromone Essence\?$/, '确认要回收 $1 为 $2 信息素精华吗？'],
    [/^Updates from (.+) to (.+)$/, '版本更新从 $1 到 $2'],
    [/^Requires (.+) Queen Chamber$/, '需要 $1 蚁后室'],
    [/^Requires (.+) Nursery$/, '需要 $1 苗圃'],
    [/^Requires (.+) Worker Ant$/, '需要 $1 工蚁'],
    [/^Have (.+) worker ants$/, '拥有 $1 工蚁'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)K EP$/, '$1K 进化点数'],
    [/^([\d\.]+)B EP$/, '$1B 进化点数'],
    [/^([\d\.]+)M EP$/, '$1M 进化点数'],
    [/^([\d\.]+)T EP$/, '$1T 进化点数'],
    [/^([\d\.]+)\/trip$/, '$1\/旅行'],
    [/^([\d\.]+)\% faster worker development$/, '工蚁发展加快 $1\%'],
    [/^([\d\.]+)\% decreased queen chamber cost$/, '蚁后室成本降低 $1\%'],
    [/^([\d\.]+)\% decreased nursery cost$/, '苗圃成本降低 $1\%'],
    [/^([\d\.]+)\% decreased worker cost$/, '工蚁成本降低 $1\%'],
    [/^([\d\.]+)\% increased larvae capacity$/, '幼虫容量提升 $1\%'],
    [/^([\d\.]+)\% increased carrying capacity$/, '运载能力提升 $1\%'],
    [/^([\d\.]+)\% increased worker production$/, '工蚁生产提升 $1\%'],
    [/^([\d\.]+)\% increased nursery production$/, '苗圃产量提升 $1\%'],
    [/^([\d\.]+)\% increased productivity$/, '生产力提升 $1\%'],
    [/^([\d\.]+)\% increased egg production$/, '蚁卵产量提升 $1\%'],
    [/^([\d\.]+)\% increased food production$/, '食物产量提升 $1\%'],
    [/^([\d\.]+)\% increased food quality$/, '食物质量提升 $1\%'],
    [/^([\d\.]+)\% HP$/, '$1\% 生命值'],
    [/^\+([\d\.]+) EP$/, '\+$1 进化点数'],
    [/^\+([\d\.]+)\% EP gain per queen chamber per evolution$/, '每次进化每个蚁后室 \+$1\% 进化点数增益'],
    [/^\+([\d\.]+)\% chance to generate a free queen chamber per tick$/, '每Tick生成一个蚁后室的几率 \+$1\%'],
    [/^([\d\.]+)\% chance to generate a free queen chamber per tick$/, '每Tick生成一个蚁后室的几率 \+$1\%'],
    [/^\+([\d\.]+)\% worker production$/, '工蚁生产 \+$1\%'],
    [/^\+([\d\.]+)\% nursery production$/, '苗圃生产 \+$1\%'],
    [/^\+([\d\.]+)\% to all stats$/, '全部属性 \+$1\%'],
    [/^\+([\d\.]+)\% to all production and special modifiers$/, '全部生产和特殊词缀 \+$1\%'],
    [/^\+([\d\.]+) base nursery production$/, '基础苗圃生产 \+$1'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) base food production$/, '\+$1 基础食物生产'],
    [/^\+([\d\.,]+) base worker production$/, '\+$1 基础工蚁生产'],
    [/^Adapt \(([\d\.,]+) pts\)$/, '改造（$1 点数）'],
    [/^Current: ([\d\.,]+)$/, '当前: $1'],
    [/^\(([\d\.,]+) items\)$/, '（$1 物品）'],
    [/^([\d\.,]+) queen chamber$/, '$1 蚁后室'],
    [/^([\d\.,]+) nurserie$/, '$1 苗圃'],
    [/^([\d\.,]+) Cycles$/, '$1 周期'],
    [/^([\d\.,]+) cycles$/, '$1 周期'],
    [/^([\d\.,]+) EP$/, '$1 进化点数'],
    [/^([\d\.,]+) slots$/, '$1 槽位'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) seconds$/, '$1 秒'],
    [/^([\d\.,]+) minute$/, '$1 分钟'],
    [/^([\d\.,]+) minutes$/, '$1 分钟'],
    [/^([\d\.,]+) hours and ([\d\.,]+) minutes$/, '$1 小时 $2 分钟'],
    [/^([\d\.,]+) hour and ([\d\.,]+) minutes$/, '$1 小时 $2 分钟'],
    [/^([\d\.,]+) points$/, '$1 点数'],
    [/^You have enough items to merge \((.+) needed\)$/, '你已经有了足够的物品去合并（需要 $1）'],
    [/^Need ([\d\.,]+) items to merge \(have ([\d\.,]+)\)$/, '需要 $1 物品以合并（拥有 $2）'],
    [/^Need at least ([\d\.,]+) items to merge \(have ([\d\.,]+)\)$/, '需要至少 $1 物品以合并（拥有 $2）'],
    [/^Need ([\d\.,]+) Cycles$/, '需要 $1 周期'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Level ([\d\.,]+)\/([\d\.,]+)$/, '等级 $1\/$2'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^Lv. ([\d\.,]+)$/, '等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Collect (.+) food in total$/, '总计收集 $1 食物'],
    [/^Play for (.+) hour in total$/, '总计游戏 $1 小时'],
    [/^Play for (.+) hours in total$/, '总计游戏 $1 小时'],
    [/^Goal: Complete (.+) objectives$/, '目标：完成 $1 目标'],
    [/^Goal: Kill (.+) bugs$/, '目标：击杀 $1 虫子'],
    [/^Goal: Kill (.+) quantum_beetle$/, '目标：击杀 $1 量子甲虫'],
    [/^Goal: Kill (.+) army_ant$/, '目标：击杀 $1 行军蚁'],
    [/^Goal: Kill (.+) tarantula$/, '目标：击杀 $1 狼蛛'],
    [/^Goal: Kill (.+) grasshopper$/, '目标：击杀 $1 蚱蜢'],
    [/^Goal: Kill (.+) galactic_moth$/, '目标：击杀 $1 银河飞蛾'],
    [/^Goal: Kill (.+) scorpion$/, '目标：击杀 $1 蝎子'],
    [/^Goal: Kill (.+) endless_ant_swarms$/, '目标：击杀 $1 无尽的蚁群'],
    [/^Goal: Kill (.+) beetle$/, '目标：击杀 $1 甲虫'],
    [/^Goal: Kill (.+) safe$/, '目标：击杀 $1 安全'],
    [/^Goal: Collect (.+) pheromone essence$/, '目标：收集 $1 信息素精华'],
    [/^Colony: (.+) increase$/, '蚁群：增加 $1'],
    [/^Nursery: (.+) increase$/, '苗圃：增加 $1'],
    [/^Worker: (.+) increase$/, '工蚁：增加 $1'],
    [/^QueenChamber: (.+) increase$/, '蚁后室：增加 $1'],
    [/^Next: (.+) Essence$/, '下一个：$1 精华'],
    [/^Next: (.+) purchases$/, '下一个：$1 购买'],
    [/^Next: (.+) food$/, '下一个：$1 食物'],
    [/^Next: (.+) ticks$/, '下一个：$1 Tick'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^(.+) food\/trip$/, '$1 食物/旅行'],
    [/^(.+) worker ants\/trip$/, '$1 工蚁/旅行'],
    [/^(.+) worker ant$/, '$1 工蚁'],
    [/^(.+) worker ants$/, '$1 工蚁'],
    [/^Available Essence$/, '可用精华'],
    [/^(.+)x Global Production multiplier permanently$/, '$1x 永久 全局生产 乘数'],
    [/^(.+)x pheromone multiplier permanently$/, '$1x 永久 信息素 乘数'],
    [/^(.+)x worker multiplier permanently$/, '$1x 永久 工蚁 乘数'],
    [/^(.+)x food multiplier permanently$/, '$1x 永久 食物 乘数'],
    [/^(.+)x soldier multiplier permanently$/, '$1x 永久 兵蚁 乘数'],
    [/^(.+) Pheromone Essence$/, '$1 信息素精华'],
    [/^(.+)K Essence$/, '$1K 精华'],
    [/^(.+) per hit$/, '$1 每次命中'],
    [/^(.+) hits$/, '$1 命中'],
    [/^(.+) ame cycles$/, '$1 游戏周期'],
    [/^(.+) slots unlocked$/, '$1 槽位已解锁'],
    [/^(.+) Bugs$/, '$1 虫子'],
    [/^(.+) Food$/, '$1 食物'],
    [/^(.+) food$/, '$1 食物'],
    [/^(.+) trips$/, '$1 旅行'],
    [/^(.+) PE$/, '$1 信息素精华'],
    [/^\+(.+) EP$/, '\+$1 进化点数'],
    [/^\+(.+) slots$/, '\+$1 槽位'],
    [/^(.+) Evolution Points$/, '$1 进化点数'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工蚁：$1\/'],

]);